name: Super Linter
on:
  pull_request:
    branches: [ master ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          FILTER_REGEX_INCLUDE: .*\.(js|yml)
          FILTER_REGEX_EXCLUDE: .*(spec|domManipulators).*
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
